version : '3'

services:
    lb:
        image: haproxy
        ports:
            - "3000:3000"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy    
    ws:
        image: chat-server
        deploy:
            replicas: 2
    redis:
        image: redis
